version: 2
sources:
  - name: raw
    database: ANALYTICS
    schema: RAW
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests: [not_null, unique]
      - name: workers
        columns:
          - name: worker_id
            tests: [not_null, unique]
      - name: bookings
        columns:
          - name: booking_id
            tests: [not_null, unique]
          - name: updated_at
            tests: [not_null]
      - name: weather
        columns:
          - name: city
          - name: date
